# Generated by Django 5.0.4 on 2024-05-23 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalizeuser',
            options={'verbose_name': 'Usuário Vitalize', 'verbose_name_plural': 'Usuários Vitalize'},
        ),
        migrations.AlterModelManagers(
            name='vitalizeuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='vitalizeuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='vitalizeuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vitalizeuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='vitalizeuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vitalizeuser',
            name='username',
        ),
        migrations.AddField(
            model_name='vitalizeuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalizeuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='vitalizeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vitalizeuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
