# Generated by Django 5.0.4 on 2024-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_vitalizeuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50, verbose_name='Permissão de Usuário')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Descrição de Permissão')),
            ],
        ),
        migrations.AddField(
            model_name='vitalizeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
