# Generated by Django 5.0.4 on 2024-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_permissions_vitalizeuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
