# Generated by Django 5.0.4 on 2024-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_vitalizeuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
