# Generated by Django 5.0.4 on 2024-08-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_vitalizeuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalizeuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='vitalizeuser',
            name='user_permissions',
        ),
    ]
