# Generated by Django 5.0.4 on 2024-08-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_remove_vitalizeuser_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_staff',
            field=models.BooleanField(default=False, editable=False, verbose_name='Colaborador Vitalize'),
        ),
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_superuser',
            field=models.BooleanField(default=False, editable=False, verbose_name='Administrador Vitalize'),
        ),
    ]
