# Generated by Django 5.0.4 on 2024-09-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_alter_vitalizeuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Colaborador Vitalize'),
        ),
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Administrador Vitalize'),
        ),
    ]
