# Generated by Django 5.0.4 on 2024-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_vitalizeuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Marque para Permitir Acesso a Área Administrativa.', verbose_name='Acesso a Área Administrativa'),
        ),
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Administrador Vitalize : Marque para dar Todas as Permissões para Este Usuário na Área Administrativa.', verbose_name='Administrador Vitalize'),
        ),
    ]
