# Generated by Django 5.0.4 on 2024-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_alter_vitalizeuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalizeuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque Essa Caixa para Ativar essa Categoria. Desmarque para Inativar.', verbose_name='Ativo/Inativo'),
        ),
    ]
