# Generated by Django 5.0.4 on 2024-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_vitalizeuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalizeuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque Essa Caixa para Ativar esse Usuário. Desmarque para Inativar.', verbose_name='Ativo/Inativo'),
        ),
    ]
