# Generated by Django 5.0.4 on 2024-08-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CashRegister', '0001_initial'),
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='sale',
            field=models.ManyToManyField(to='Sales.sales', verbose_name='Venda'),
        ),
    ]
