# Generated by Django 5.0.4 on 2024-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0005_alter_cashregister_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='cash_out',
            field=models.ManyToManyField(
                blank=True, to='CashRegister.cashout', verbose_name='Sangria'),
        ),
    ]
