# Generated by Django 5.0.4 on 2024-09-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0006_alter_cashregister_cash_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Caixa (R$)'),
        ),
    ]
