# Generated by Django 5.0.4 on 2024-09-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0007_alter_cashout_value_alter_cashregister_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Aberto/Fechado'),
        ),
    ]
