# Generated by Django 5.0.4 on 2024-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0010_alter_cashregister_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashregister',
            old_name='sale',
            new_name='sales',
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='cash_out',
            field=models.ManyToManyField(blank=True, help_text='Faça uma Sangria no Caixa Escolhendo uma Opção e Salvando.', to='CashRegister.cashout', verbose_name='Sangria'),
        ),
    ]
