# Generated by Django 5.0.4 on 2024-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0013_alter_cashregister_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='cash',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor do Caixa (R$)'),
        ),
    ]
