# Generated by Django 5.0.4 on 2024-09-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0016_alter_cashout_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='cash_out',
        ),
    ]
