# Generated by Django 5.0.4 on 2024-09-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0018_remove_cashout_description_cashout_cashregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='cashregister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CashRegister.cashregister', verbose_name='Caixa'),
        ),
    ]
