# Generated by Django 5.0.4 on 2024-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0019_alter_cashout_cashregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashout',
            name='description',
            field=models.CharField(default='Descrição da Sangria', max_length=150, verbose_name='Descrição de Sangria'),
            preserve_default=False,
        ),
    ]
