# Generated by Django 5.0.4 on 2024-10-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0021_cashin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashin',
            options={'verbose_name': 'Entrada Vitalize', 'verbose_name_plural': 'Entradas Vitalize'},
        ),
    ]
