# Generated by Django 5.0.4 on 2024-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0022_alter_cashin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashin',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Descrição de Entrada'),
        ),
    ]
