# Generated by Django 5.0.4 on 2024-08-21 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalizelogs',
            options={'verbose_name': 'Log Vitalize', 'verbose_name_plural': 'Logs Vitalize'},
        ),
        migrations.AlterField(
            model_name='vitalizelogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
