# Generated by Django 5.0.4 on 2024-08-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('cover_path', models.ImageField(upload_to='services/%Y/%m/%d/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
            ],
            options={
                'verbose_name': 'Serviço Vitalize',
                'verbose_name_plural': 'Serviços Vitalize',
            },
        ),
        migrations.AlterModelOptions(
            name='schedules',
            options={'verbose_name': 'Agendamento Vitalize', 'verbose_name_plural': 'Agendamentos Vitalize'},
        ),
        migrations.AddField(
            model_name='schedules',
            name='service',
            field=models.ManyToManyField(to='Schedules.services', verbose_name='Serviço'),
        ),
    ]
