# Generated by Django 5.0.4 on 2024-09-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0006_alter_schedules_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cover_path',
            field=models.ImageField(upload_to='services/%Y/%m/%d/', verbose_name='Imagem do Serviço'),
        ),
    ]
