# Generated by Django 5.0.4 on 2024-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0007_alter_services_cover_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='status',
            field=models.BooleanField(default=True, help_text='Marcado/Desmarcado', verbose_name='Status'),
        ),
    ]
