# Generated by Django 5.0.4 on 2024-09-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0010_services_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Preço Total (R$)'),
        ),
    ]
