# Generated by Django 5.0.4 on 2024-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0012_alter_schedules_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço Total (R$)'),
        ),
    ]
