# Generated by Django 5.0.4 on 2024-11-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0014_alter_schedules_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedule_date',
            field=models.DateField(verbose_name='Data Agendada'),
        ),
    ]
