# Generated by Django 5.0.4 on 2024-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0015_alter_schedules_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Horário de Agendamento')),
                ('is_active', models.BooleanField(default=True, help_text='Marque Essa Caixa para Ativar esse Horário. Desmarque para Inativar.', verbose_name='Ativo/Inativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
            ],
        ),
        migrations.AlterField(
            model_name='schedules',
            name='status',
            field=models.BooleanField(default=True, help_text='Agendado/Finalizado', verbose_name='Status'),
        ),
    ]
