# Generated by Django 5.0.4 on 2024-11-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0017_alter_scheduletime_options_schedules_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletime',
            name='time',
            field=models.TimeField(unique=True, verbose_name='Horário de Agendamento'),
        ),
    ]
