# Generated by Django 5.0.4 on 2024-11-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0020_alter_scheduletime_is_picked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletime',
            name='is_picked',
            field=models.BooleanField(default=False, verbose_name='Selecionado'),
        ),
    ]
