# Generated by Django 5.0.4 on 2024-11-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0021_alter_scheduletime_is_picked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedule_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Schedules.scheduletime', verbose_name='Horário Agendado'),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='is_picked',
            field=models.BooleanField(default=False, help_text='Indica se este Horário já foi Escolhido por alguém.', verbose_name='Selecionado'),
        ),
    ]
