# Generated by Django 5.0.4 on 2024-11-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0022_alter_schedules_schedule_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletime',
            name='is_picked',
        ),
        migrations.CreateModel(
            name='ScheduleDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data Agendada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Schedules.scheduletime', verbose_name='Horário Agendado')),
            ],
            options={
                'verbose_name': 'Data e Hora Vitalize',
                'verbose_name_plural': 'Data e Hora Vitalize',
            },
        ),
    ]
