# Generated by Django 5.0.4 on 2024-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0023_remove_scheduletime_is_picked_scheduledatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Marque para Cancelar o Agendamento.', verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='status',
            field=models.BooleanField(default=True, help_text='Agendado/Finalizado.', verbose_name='Status'),
        ),
    ]
