# Generated by Django 5.0.4 on 2024-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notifications_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo/Inativo'),
        ),
    ]
