# Generated by Django 5.0.4 on 2024-10-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_alter_notifications_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='is_active',
        ),
    ]
