# Generated by Django 5.0.4 on 2024-08-21 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_price'),
        ('Sales', '0002_alter_sales_total_price'),
        ('Schedules', '0003_alter_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='Products.products', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Schedules.schedules', verbose_name='Agendamento'),
        ),
    ]
