# Generated by Django 5.0.4 on 2024-08-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_sales_product_alter_sales_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço (R$)'),
        ),
    ]
