# Generated by Django 5.0.4 on 2024-09-04 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_sales_product'),
        ('Schedules', '0005_alter_schedules_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schedules.schedules', verbose_name='Agendamento'),
        ),
    ]
