# Generated by Django 5.0.4 on 2024-09-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_categories_is_active_alter_products_is_active'),
        ('Sales', '0006_alter_sales_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttypes',
            options={'verbose_name': 'Tipo de Pagamento Vitalize', 'verbose_name_plural': 'Tipos de Pagamento Vitalize'},
        ),
        migrations.AddField(
            model_name='paymenttypes',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque Essa Caixa para Ativar esse Tipo de Pagamento. Desmarque para Inativar.', verbose_name='Ativo/Inativo'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ManyToManyField(blank=True, to='Products.products', verbose_name='Produto(s)'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço Total (R$)'),
        ),
    ]
