# Generated by Django 5.0.4 on 2024-09-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_alter_paymenttypes_options_paymenttypes_is_active_and_more'),
        ('Schedules', '0007_alter_services_cover_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Schedules.schedules', verbose_name='Agendamento'),
        ),
    ]
