# Generated by Django 5.0.4 on 2024-09-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_rename_payment_sales_payment_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product',
            new_name='products',
        ),
    ]
