# Generated by Django 5.0.4 on 2024-09-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_rename_product_sales_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, verbose_name='Preço Total (R$)'),
        ),
    ]
