# Generated by Django 5.0.4 on 2024-09-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_alter_sales_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Preço Total (R$)'),
        ),
    ]
