# Generated by Django 5.0.4 on 2024-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0012_alter_sales_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, verbose_name='Preço Total (R$)'),
            preserve_default=False,
        ),
    ]
