# Generated by Django 5.0.4 on 2024-09-25 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0015_alter_sales_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='payment_types',
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Sales.paymenttypes', verbose_name='Tipo de Pagamento'),
            preserve_default=False,
        ),
    ]
