# Generated by Django 5.0.4 on 2024-09-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_remove_categories_products_ca_is_acti_2c57f2_idx'),
        ('Sales', '0016_remove_sales_payment_types_sales_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=7, verbose_name='Preço Total (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.products', verbose_name='Produto da Venda')),
            ],
        ),
    ]
