# Generated by Django 5.0.4 on 2024-09-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0017_saleitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Item da Venda', 'verbose_name_plural': 'Items da Venda'},
        ),
    ]
