# Generated by Django 5.0.4 on 2024-09-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0018_alter_saleitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Sales.sales', verbose_name='Venda'),
            preserve_default=False,
        ),
    ]
