# Generated by Django 5.0.4 on 2024-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0019_saleitem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço Total (R$)'),
        ),
    ]
