# Generated by Django 5.0.4 on 2024-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_sales_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
    ]
