# Generated by Django 5.0.4 on 2024-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Mostrar na Vitrine'),
        ),
    ]
