# Generated by Django 5.0.4 on 2024-09-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_categories_is_active_products_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
    ]
