# Generated by Django 5.0.4 on 2024-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque Essa Caixa para Ativar essa Categoria. Desmarque para Desativar', verbose_name='Ativo/Inativo'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque Essa Caixa para Ativar esse Produto. Desmarque para Desativar', verbose_name='Ativo/Inativo'),
        ),
    ]
