# Generated by Django 5.0.4 on 2024-09-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_categories_is_active_alter_products_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque Essa Caixa para Ativar essa Categoria. Desmarque para Inativar.', verbose_name='Ativo/Inativo'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque Essa Caixa para Ativar esse Produto. Desmarque para Inativar.', verbose_name='Ativo/Inativo'),
        ),
    ]
