# Generated by Django 5.0.4 on 2024-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_categories_is_active_alter_products_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='show',
            field=models.BooleanField(default=True, help_text='Marque para Mostrar o Produto na Vitrine do Site.', verbose_name='Mostrar na Vitrine'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['is_active'], name='Products_ca_is_acti_2c57f2_idx'),
        ),
    ]
