# Generated by Django 5.0.4 on 2024-09-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_alter_products_show_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categories',
            name='Products_ca_is_acti_2c57f2_idx',
        ),
    ]
